class StaticDataService {
  getProductCategories() {
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: [
          { label: "Dental", value: "dental" },
          { label: "Detergents", value: "detergents" },
        ],
      });
    });
  }

  getSKUBasedOnCategory(category) {
    let obj = {};
    if (category === "dental") {
      obj.sku = "ABC123";
      obj.id = "12";
    } else if (category === "detergents") {
      obj.sku = "Tide";
      obj.id = "13";
    }
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: obj,
      });
    });
  }

  getAllProducts() {
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: [
          {
            id: "70a34114-1c75-4592-9866-26fb94b5a402",
            product_category: "Dental",
            sku_code: "ABC123",
            uom: "Case",
            period: "23-Apr-2020",
            stats_forecast: 27,
          },
          {
            id: "b4fa6945-15b8-4ded-8ffb-82c9015f5460",
            product_category: "Detergents",
            sku_code: "Tide",
            uom: "Case",
            period: "12-Nov-2020",
            stats_forecast: 93,
          },
          {
            id: "4513cec3-bc5f-4ce3-aee5-7acec96d5e65",
            product_category: "Dental",
            sku_code: "ABC123",
            uom: "Case",
            period: "05-Jul-2020",
            stats_forecast: 59,
          },
          {
            id: "243832d7-7a0e-4531-995c-9a2998dcec2a",
            product_category: "Detergents",
            sku_code: "Tide",
            uom: "Case",
            period: "21-Mar-2020",
            stats_forecast: 39,
          },
          {
            id: "ccfc31a1-d6b2-4b0b-8fa2-92d7b25456b0",
            product_category: "Dental",
            sku_code: "ABC123",
            uom: "Case",
            period: "03-Sep-2020",
            stats_forecast: 20,
          },
          {
            id: "7b59a582-31cf-4b87-8b58-fb006087b17c",
            product_category: "Detergents",
            sku_code: "Tide",
            uom: "Case",
            period: "24-May-2020",
            stats_forecast: 29,
          },
          {
            id: "4b648056-cd3a-474f-b28c-455610238ea7",
            product_category: "Dental",
            sku_code: "ABC123",
            uom: "Case",
            period: "08-Mar-2020",
            stats_forecast: 70,
          },
          {
            id: "d757a278-0ecd-4c9b-901f-d6e4c716ee32",
            product_category: "Detergents",
            sku_code: "Tide",
            uom: "Case",
            period: "22-Jun-2020",
            stats_forecast: 53,
          },
          {
            id: "03f5ad06-fa90-41d9-b5e4-c615d4dd1c92",
            product_category: "Dental",
            sku_code: "ABC123",
            uom: "Case",
            period: "11-Oct-2020",
            stats_forecast: 28,
          },
          {
            id: "3f4c09fc-a381-4a78-b489-f0ec78c8b6bb",
            product_category: "Detergents",
            sku_code: "Tide",
            uom: "Case",
            period: "15-Jan-2021",
            stats_forecast: 98,
          },
        ],
      });
    });
  }

  getAllMasterSKUData() {
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: [
          {
            id: 1,
            category: "Dental",
            sku: "ABC123",
            sku_description: "ABC123",
            sourcing_location: "Bangalore KA",
            uom: "Case",
            abc_class: "A",
            xyz_class: "X",
            movement_class: "Slow Moving",
            purchase_price: "$140.06",
            sell_price: "$357.55",
            margin: 40.19,
            moq: 17,
            soh: 370,
            soh_days: 11,
            avg_demand_per_day: 75.0,
            stock_value: 1425,
            stock_transit: 71,
            open_po_qty: 142,
            open_so_qty: 293,
            lead_time_in_days: 10,
            roq_units: 70,
            safety_stock_units: 283,
            min_units: 419,
            max_units: 701,
            tm_forecast_accuracy: 55.9,
            shortage_units: 121.9,
            excess_units: 32,
            target_fill: 35,
            actual_fill: 78,
          },
          {
            id: 2,
            category: "Detergents",
            sku: "ABC293",
            sku_description: "ABC293",
            sourcing_location: "Mumbai MH",
            uom: "Case",
            abc_class: "B",
            xyz_class: "Y",
            movement_class: "Moderately Moving",
            purchase_price: "$128.84",
            sell_price: "$343.15",
            margin: 92.82,
            moq: 19,
            soh: 931,
            soh_days: 14,
            avg_demand_per_day: 201.0,
            stock_value: 1516,
            stock_transit: 48,
            open_po_qty: 193,
            open_so_qty: 344,
            lead_time_in_days: 7,
            roq_units: 122,
            safety_stock_units: 415,
            min_units: 143,
            max_units: 1102,
            tm_forecast_accuracy: 56.1,
            shortage_units: 7.3,
            excess_units: 14,
            target_fill: 34,
            actual_fill: 27,
          },
          {
            id: 3,
            category: "Dental",
            sku: "ABC453",
            sku_description: "ABC453",
            sourcing_location: "Chennai TN",
            uom: "Case",
            abc_class: "C",
            xyz_class: "Z",
            movement_class: "Moderately Moving",
            purchase_price: "$141.36",
            sell_price: "$307.24",
            margin: 36.32,
            moq: 100,
            soh: 156,
            soh_days: 12,
            avg_demand_per_day: 163.0,
            stock_value: 1386,
            stock_transit: 21,
            open_po_qty: 136,
            open_so_qty: 341,
            lead_time_in_days: 5,
            roq_units: 164,
            safety_stock_units: 455,
            min_units: 368,
            max_units: 532,
            tm_forecast_accuracy: 58.1,
            shortage_units: 90.7,
            excess_units: 8,
            target_fill: 73,
            actual_fill: 80,
          },
          {
            id: 4,
            category: "Detergents",
            sku: "ABC983",
            sku_description: "ABC983",
            sourcing_location: "Bangalore KA",
            uom: "Case",
            abc_class: "A",
            xyz_class: "X",
            movement_class: "Moderately Moving",
            purchase_price: "$146.89",
            sell_price: "$313.12",
            margin: 51.48,
            moq: 58,
            soh: 980,
            soh_days: 15,
            avg_demand_per_day: 119.3,
            stock_value: 1407,
            stock_transit: 68,
            open_po_qty: 141,
            open_so_qty: 372,
            lead_time_in_days: 6,
            roq_units: 125,
            safety_stock_units: 420,
            min_units: 108,
            max_units: 1250,
            tm_forecast_accuracy: 57.9,
            shortage_units: 12.9,
            excess_units: 33,
            target_fill: 20,
            actual_fill: 54,
          },
          {
            id: 5,
            category: "Dental",
            sku: "ABC948",
            sku_description: "ABC948",
            sourcing_location: "Mumbai MH",
            uom: "Case",
            abc_class: "B",
            xyz_class: "Y",
            movement_class: "Slow Moving",
            purchase_price: "$161.42",
            sell_price: "$316.97",
            margin: 81.47,
            moq: 96,
            soh: 1484,
            soh_days: 8,
            avg_demand_per_day: 225.5,
            stock_value: 1156,
            stock_transit: 97,
            open_po_qty: 193,
            open_so_qty: 327,
            lead_time_in_days: 1,
            roq_units: 131,
            safety_stock_units: 381,
            min_units: 462,
            max_units: 1001,
            tm_forecast_accuracy: 53.4,
            shortage_units: 114.6,
            excess_units: 34,
            target_fill: 50,
            actual_fill: 66,
          },
          {
            id: 6,
            category: "Detergents",
            sku: "ABC332",
            sku_description: "ABC332",
            sourcing_location: "Chennai TN",
            uom: "Case",
            abc_class: "C",
            xyz_class: "Z",
            movement_class: "Slow Moving",
            purchase_price: "$141.75",
            sell_price: "$398.77",
            margin: 24.16,
            moq: 98,
            soh: 1145,
            soh_days: 14,
            avg_demand_per_day: 122.5,
            stock_value: 1811,
            stock_transit: 96,
            open_po_qty: 192,
            open_so_qty: 368,
            lead_time_in_days: 5,
            roq_units: 161,
            safety_stock_units: 535,
            min_units: 274,
            max_units: 761,
            tm_forecast_accuracy: 54.2,
            shortage_units: 35.7,
            excess_units: 15,
            target_fill: 61,
            actual_fill: 51,
          },
          {
            id: 7,
            category: "Dental",
            sku: "ABC123",
            sku_description: "ABC123",
            sourcing_location: "Bangalore KA",
            uom: "Case",
            abc_class: "A",
            xyz_class: "X",
            movement_class: "Slow Moving",
            purchase_price: "$127.91",
            sell_price: "$312.11",
            margin: 78.13,
            moq: 72,
            soh: 444,
            soh_days: 4,
            avg_demand_per_day: 290.8,
            stock_value: 1982,
            stock_transit: 94,
            open_po_qty: 199,
            open_so_qty: 349,
            lead_time_in_days: 3,
            roq_units: 158,
            safety_stock_units: 268,
            min_units: 314,
            max_units: 1208,
            tm_forecast_accuracy: 59.7,
            shortage_units: 20.1,
            excess_units: 10,
            target_fill: 63,
            actual_fill: 20,
          },
          {
            id: 8,
            category: "Detergents",
            sku: "ABC293",
            sku_description: "ABC293",
            sourcing_location: "Mumbai MH",
            uom: "Case",
            abc_class: "B",
            xyz_class: "Y",
            movement_class: "Moderately Moving",
            purchase_price: "$195.00",
            sell_price: "$394.24",
            margin: 99.98,
            moq: 76,
            soh: 841,
            soh_days: 5,
            avg_demand_per_day: 216.6,
            stock_value: 1209,
            stock_transit: 94,
            open_po_qty: 189,
            open_so_qty: 363,
            lead_time_in_days: 7,
            roq_units: 86,
            safety_stock_units: 596,
            min_units: 145,
            max_units: 667,
            tm_forecast_accuracy: 55.3,
            shortage_units: 116.0,
            excess_units: 5,
            target_fill: 76,
            actual_fill: 36,
          },
          {
            id: 9,
            category: "Dental",
            sku: "ABC453",
            sku_description: "ABC453",
            sourcing_location: "Chennai TN",
            uom: "Case",
            abc_class: "C",
            xyz_class: "Z",
            movement_class: "Moderately Moving",
            purchase_price: "$133.14",
            sell_price: "$345.44",
            margin: 39.47,
            moq: 78,
            soh: 1370,
            soh_days: 7,
            avg_demand_per_day: 68.5,
            stock_value: 1439,
            stock_transit: 46,
            open_po_qty: 200,
            open_so_qty: 366,
            lead_time_in_days: 3,
            roq_units: 95,
            safety_stock_units: 141,
            min_units: 281,
            max_units: 1287,
            tm_forecast_accuracy: 56.6,
            shortage_units: 40.1,
            excess_units: 26,
            target_fill: 36,
            actual_fill: 22,
          },
          {
            id: 10,
            category: "Detergents",
            sku: "ABC983",
            sku_description: "ABC983",
            sourcing_location: "Bangalore KA",
            uom: "Case",
            abc_class: "A",
            xyz_class: "X",
            movement_class: "Moderately Moving",
            purchase_price: "$120.86",
            sell_price: "$316.46",
            margin: 30.23,
            moq: 61,
            soh: 795,
            soh_days: 1,
            avg_demand_per_day: 165.4,
            stock_value: 1898,
            stock_transit: 23,
            open_po_qty: 151,
            open_so_qty: 286,
            lead_time_in_days: 4,
            roq_units: 73,
            safety_stock_units: 364,
            min_units: 406,
            max_units: 1198,
            tm_forecast_accuracy: 52.9,
            shortage_units: 36.6,
            excess_units: 19,
            target_fill: 60,
            actual_fill: 78,
          },
        ],
      });
    });
  }
}

export default new StaticDataService();
